In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

# Part 1 - Data Preprocessing

# Importing the Dataset

In [3]:
data=pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\heart_disease dataset.csv")

In [4]:
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [6]:
data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [7]:
data.median()

age          56.0
sex           1.0
cp            1.0
trestbps    130.0
chol        240.0
fbs           0.0
restecg       1.0
thalach     152.0
exang         0.0
oldpeak       0.8
slope         1.0
ca            0.0
thal          2.0
target        1.0
dtype: float64

In [8]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
data=pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\heart_disease dataset.csv")
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [10]:
print(x)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [11]:
print(y)

[0 0 0 ... 0 1 0]


# Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [14]:
print(x_train)

[[-1.40503359  0.64895597  1.97748631 ...  0.97028605  1.17427458
  -0.5144228 ]
 [ 1.26270023 -1.5409366   1.01170979 ... -0.6668221   0.21616
  -0.5144228 ]
 [-0.18232226  0.64895597  1.01170979 ...  0.97028605  2.13238916
  -0.5144228 ]
 ...
 [ 1.15154465  0.64895597  1.97748631 ... -0.6668221   0.21616
  -0.5144228 ]
 [ 1.3738558   0.64895597 -0.91984324 ... -0.6668221  -0.74195458
  -0.5144228 ]
 [ 0.59576677  0.64895597  1.01170979 ... -0.6668221  -0.74195458
  -0.5144228 ]]


# Part 2 - Building the ANN

# ##Initializing the ANN

In [15]:
ann=tf.keras.models.Sequential()

### Adding the first Input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

### Adding 2ND Hidden Layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

### Adding the Output Layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

# Part 3 - Training the ANN

### compliling the ANN

In [19]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

### Training the ANN on the Training set

In [20]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
26/26 [==============================] - 1s 2ms/step - loss: 0.8408 - accuracy: 0.4854
Epoch 2/100
26/26 [==============================] - 0s 2ms/step - loss: 0.7530 - accuracy: 0.5171
Epoch 3/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6984 - accuracy: 0.5805
Epoch 4/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6652 - accuracy: 0.6171
Epoch 5/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6397 - accuracy: 0.6439
Epoch 6/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6181 - accuracy: 0.6512
Epoch 7/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5978 - accuracy: 0.6756
Epoch 8/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5779 - accuracy: 0.7000
Epoch 9/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5578 - accuracy: 0.7244
Epoch 10/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5387 - accuracy: 0.7451
Epoch 11/

26/26 [==============================] - 0s 2ms/step - loss: 0.2395 - accuracy: 0.8951
Epoch 83/100
26/26 [==============================] - 0s 2ms/step - loss: 0.2380 - accuracy: 0.9012
Epoch 84/100
26/26 [==============================] - 0s 2ms/step - loss: 0.2365 - accuracy: 0.9049
Epoch 85/100
26/26 [==============================] - 0s 2ms/step - loss: 0.2353 - accuracy: 0.9049
Epoch 86/100
26/26 [==============================] - 0s 1ms/step - loss: 0.2339 - accuracy: 0.9049
Epoch 87/100
26/26 [==============================] - 0s 2ms/step - loss: 0.2331 - accuracy: 0.9049
Epoch 88/100
26/26 [==============================] - 0s 2ms/step - loss: 0.2318 - accuracy: 0.9073
Epoch 89/100
26/26 [==============================] - 0s 2ms/step - loss: 0.2315 - accuracy: 0.9073
Epoch 90/100
26/26 [==============================] - 0s 2ms/step - loss: 0.2296 - accuracy: 0.9098
Epoch 91/100
26/26 [==============================] - 0s 2ms/step - loss: 0.2287 - accuracy: 0.9122
Epoch 92/100


# Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

 **Solution**

### Predicting the Test set results

In [21]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
# print(y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]

### Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[91  7]
 [ 8 99]]


0.926829268292683