In [1]:
import numpy as np

In [20]:
s=np.array([2,3,4,5,6,7,8])
print(s)
print(s.dtype)

[2 3 4 5 6 7 8]
int32


In [22]:
s2=np.array([2.5,3,4,5,6,7,8])
print(s2.dtype)

float64


In [21]:
s3=np.array([2.5,3,4,"5",6,7,8])
print(s3.dtype)

<U32


In [18]:
a=np.array(5)             # Zero dimension array
print(a.dtype)
print(a.ndim)     

int32
0


In [26]:
a1=np.array([2,3,4,5,6,7])     # One dimensional array
print(a1.ndim)

1


In [28]:
a2=np.array([[2,3,4,5,6]])      # Two dimensional array
print(a2.ndim)

2


In [34]:
a3=np.array([[[2,2,2],[3,3,3],[4,4,4]]])
print(a3)
print(a3.ndim)

[[[2 2 2]
  [3 3 3]
  [4 4 4]]]
3


In [33]:
print(a3.shape)

(1, 3, 3)


In [37]:
a4=np.array([[[2,2,2],[3,3,3],[4,4,4]],[[2,2,2],[3,3,3],[4,4,4]]])
print(a4)
print(a4.ndim)

[[[2 2 2]
  [3 3 3]
  [4 4 4]]

 [[2 2 2]
  [3 3 3]
  [4 4 4]]]
3


In [38]:
print(a4.shape)

(2, 3, 3)


In [40]:
a_4d=np.array([[[[4,4,4],[4,4,4],[4,4,4]],[[4,4,4],[4,4,4],[4,4,4]]]])
print(a_4d)
print(a_4d.ndim)

[[[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]]
4


In [42]:
print(a_4d.shape)

(1, 2, 3, 3)


In [45]:
at=np.array([[[[4,4,4],[4,4,4],[4,4,4]]]])
print(at)
print(at.ndim)
print(at.shape)

[[[[4 4 4]
   [4 4 4]
   [4 4 4]]]]
4
(1, 1, 3, 3)


In [53]:
ar=np.array([[[[11,12,13],[14,15,16]],[[11,12,13],[14,15,16]]],[[[11,12,13],[14,15,16]],[[11,12,13],[14,15,16]]]])
print(ar)

[[[[11 12 13]
   [14 15 16]]

  [[11 12 13]
   [14 15 16]]]


 [[[11 12 13]
   [14 15 16]]

  [[11 12 13]
   [14 15 16]]]]


In [54]:
print(ar.shape)

(2, 2, 2, 3)
