In [1]:
import numpy as np

In [2]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.split(a,2)         #for equal division 

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [8]:
np.array_split(a,5)      #for unequal division

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [12]:
np.hsplit(a,2)    #only used for equal division  and horizontal array

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [17]:
b=np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
np.vsplit(b,2)               #vertical array

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [19]:
#arithmatic operator

In [20]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [21]:
np.shape(a)

(3, 3)

In [22]:
np.shape(b)

(3, 3)

In [23]:
np.add(a,b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [28]:
c=np.array([10,20,30])
np.shape(c)

(3,)

In [29]:
np.add(a,c)


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [30]:
np.subtract(a,b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np.multiply(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.multiply(a,c)

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

In [35]:
np.divide(a,b)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [36]:
np.divide(a,c)

array([[0.1 , 0.1 , 0.1 ],
       [0.4 , 0.25, 0.2 ],
       [0.7 , 0.4 , 0.3 ]])

In [37]:
np.power(a,c)

array([[          1,     1048576, -1010140999],
       [    1048576,  1977800241,  1073741824],
       [  282475249,           0, -1830685263]], dtype=int32)

In [40]:
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [41]:
np.mod(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [43]:
np.mod(a,10)     #mod only reflect integer

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [44]:
np.reciprocal(a,b)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [73]:
c=np.array([2+3j,2+4j])
c
np.real(c)

array([2., 2.])

In [74]:
np.imag(c)

array([3., 4.])

In [75]:
np.conjugate(c)

array([2.-3.j, 2.-4.j])

In [46]:
#indexing and slicing
a=np.array([10,20,30,40,50,60])

In [47]:
print(a[::])   #all he row

[10 20 30 40 50 60]


In [48]:
a[::2]

array([10, 30, 50])

In [49]:
a[:4]

array([10, 20, 30, 40])

In [50]:
a[2:5]

array([30, 40, 50])

In [53]:
a[-3:-1]    #negative indexing start l to r

array([40, 50])

In [52]:
a[:]

array([10, 20, 30, 40, 50, 60])

In [60]:
a[-1::-1]      #[-1:starting:step]

array([60, 50, 40, 30, 20, 10])

In [62]:
a[-2::-2]      #[-1:starting:step]

array([50, 30, 10])

In [56]:
#for 2 dim

In [57]:
b=np.array([[11,22,33],[44,55,66]])
b

array([[11, 22, 33],
       [44, 55, 66]])

In [58]:
b[0,0:3]     #[row,for that row]

array([11, 22, 33])

In [61]:
b[1,2:]

array([66])

In [63]:
b[0:2,0:2]

array([[11, 22],
       [44, 55]])

In [70]:
c=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,2,3]]])
c

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100,   2,   3]]])

In [71]:
c[1,0,0:2]    #[plane,no.array of that plane(row),element]

array([70, 80])

In [72]:
c[0,1,1:]

array([50, 60])

# pandas library

In [76]:
import pandas as pd

working on large dataset

# series

In [87]:
# series
l=[1,2,3,4,5]
l1=pd.Series(l,index=["i","ii","iii","iv","v"])    #also we change indexing
l1

i      1
ii     2
iii    3
iv     4
v      5
dtype: int64

In [88]:
type(l1)

pandas.core.series.Series

In [89]:
l1

i      1
ii     2
iii    3
iv     4
v      5
dtype: int64

In [90]:
#1)empty series
s=pd.Series()     #error because series is empty
s

C:\Users\Acer\AppData\Local\Temp/ipykernel_3020/3049211035.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s=pd.Series()


Series([], dtype: float64)

In [95]:
#2)series using array
a=np.array([1,2,3,4,5])
a1=pd.Series(a)
a1

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [96]:
type(a1)

pandas.core.series.Series

In [97]:
#convert into series using dictionary
dict1={"a":10,"b":20,"c":30,"d":40}      #"keys":value
s=pd.Series(dict1)
s

a    10
b    20
c    30
d    40
dtype: int64

In [99]:
#convert into series using list with tuple
d1=[("a",10),("b",20),("c",30),("d",40)]
s1=pd.Series(d1)
s1

0    (a, 10)
1    (b, 20)
2    (c, 30)
3    (d, 40)
dtype: object

# data frame

In [101]:
# create dataframe using dictionary
d={"name":["abc","def","ghi"],"perc":[70,75,80],"branch":["cs","IT","Ece"]}
df=pd.DataFrame(d)
df

name  perc branch
0  abc    70     cs
1  def    75     IT
2  ghi    80    Ece

In [104]:
# create dataframe using list of tuple
d1=[("abc",10,"csv"),("ghi",80,"tce"),("ipl",60,"jpg")]     
pd.DataFrame(d1)

0   1    2
0  abc  10  csv
1  ghi  80  tce
2  ipl  60  jpg

In [107]:
data1=pd.read_excel(r"C:\Users\Acer\Documents\Time Management JPM 26-2-22.xlsx")
data1

Name (Original Name)                      User Email  \
0    AYYAPPAN SENTHIVEL.S     ayyappansenthivel@gmail.com   
1            Nitin Yewale       nitinyewale7773@gmail.com   
2          Priyanka Baral       priyankabaral732@gmil.com   
3                kaviya v        v.kaviya071997@gmail.com   
4      Veena M Shellikeri            varshams68@gmail.com   
..                    ...                             ...   
162          Ramesh Sagar       sagarramesh1805@gmail.com   
163   Aayusha Suryawanshi  aayushasuryawanshi97@gmail.com   
164     Manjushree Shinde     shindemanjushree4@gmail.com   
165       MATHIYAZHAGAN T          mstmathimech@gmail.com   
166    Nithya Karthikeyan          nithi09csc26@gmail.com   

     Total Duration (Minutes) Guest  Age   Batch No  
0                         101   Yes   22       6260  
1                          78   Yes   23  2021-6750  
2                         115   Yes   21       6821  
3                         113   Yes   24  2021-6709  
4                         125   Yes   24       6141  
..                        ...   ...  ...        ...  
162                        85   Yes   23       6532  
163                        84   Yes   25       6532  
164                        80   Yes   24       6532  
165                         5   Yes   23       6260  
166                         4   Yes   29      57688  

[167 rows x 6 columns]

In [113]:
type(data1)

pandas.core.frame.DataFrame

In [110]:
data2=pd.read_csv(r"C:\Users\Acer\Documents\Credit_Risk_data.csv")
data2

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [114]:
type(data2)

pandas.core.frame.DataFrame

In [111]:
data2.shape

(614, 13)

In [112]:
data2.describe()   #it only works on integer data

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [115]:
data2.describe(include="all")

Loan_ID Gender Married Dependents Education Self_Employed  \
count        614    601     611        599       614           582   
unique       614      2       2          4         2             2   
top     LP001002   Male     Yes          0  Graduate            No   
freq           1    489     398        345       480           500   
mean         NaN    NaN     NaN        NaN       NaN           NaN   
std          NaN    NaN     NaN        NaN       NaN           NaN   
min          NaN    NaN     NaN        NaN       NaN           NaN   
25%          NaN    NaN     NaN        NaN       NaN           NaN   
50%          NaN    NaN     NaN        NaN       NaN           NaN   
75%          NaN    NaN     NaN        NaN       NaN           NaN   
max          NaN    NaN     NaN        NaN       NaN           NaN   

        ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count        614.000000         614.000000  592.000000         600.00000   
unique              NaN                NaN         NaN               NaN   
top                 NaN                NaN         NaN               NaN   
freq                NaN                NaN         NaN               NaN   
mean        5403.459283        1621.245798  146.412162         342.00000   
std         6109.041673        2926.248369   85.587325          65.12041   
min          150.000000           0.000000    9.000000          12.00000   
25%         2877.500000           0.000000  100.000000         360.00000   
50%         3812.500000        1188.500000  128.000000         360.00000   
75%         5795.000000        2297.250000  168.000000         360.00000   
max        81000.000000       41667.000000  700.000000         480.00000   

        Credit_History Property_Area Loan_Status  
count       564.000000           614         614  
unique             NaN             3           2  
top                NaN     Semiurban           Y  
freq               NaN           233         422  
mean          0.842199           NaN         NaN  
std           0.364878           NaN         NaN  
min           0.000000           NaN         NaN  
25%           1.000000           NaN         NaN  
50%           1.000000           NaN         NaN  
75%           1.000000           NaN         NaN  
max           1.000000           NaN         NaN

In [119]:
data2.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [118]:
data2.tail(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
604            12000                0.0       496.0             360.0   
605             2400             3800.0         NaN             180.0   
606             3400             2500.0       173.0             360.0   
607             3987             1411.0       157.0             360.0   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
604             1.0     Semiurban           Y  
605             1.0         Urban           N  
606             1.0     Semiurban           Y  
607             1.0         Rural           Y  
608             1.0         Rural           Y  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [120]:
data2.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [121]:
data2.corr()

ApplicantIncome  CoapplicantIncome  LoanAmount  \
ApplicantIncome           1.000000          -0.116605    0.570909   
CoapplicantIncome        -0.116605           1.000000    0.188619   
LoanAmount                0.570909           0.188619    1.000000   
Loan_Amount_Term         -0.045306          -0.059878    0.039447   
Credit_History           -0.014715          -0.002056   -0.008433   

                   Loan_Amount_Term  Credit_History  
ApplicantIncome           -0.045306       -0.014715  
CoapplicantIncome         -0.059878       -0.002056  
LoanAmount                 0.039447       -0.008433  
Loan_Amount_Term           1.000000        0.001470  
Credit_History             0.001470        1.000000